# yaml-language-server: $schema=https://raw.githubusercontent.com/oapi-codegen/oapi-codegen/HEAD/configuration-schema.json
package: mattermost
output: mattermost.gen.go
generate:
  models: true
  client: true